"use client"

import { useMemo, useState } from "react"

import WgetCommandBuilder, { DEFAULT_URL, deriveCommandUrl } from "@/components/wget-command-builder"

const DEFAULT_HOSTNAME = DEFAULT_URL.replace(/^https?:\/\//, "")

const getHostnameFromUrl = (url: string) => {
  try {
    const hostname = new URL(url).hostname
    return hostname || DEFAULT_HOSTNAME
  } catch {
    return DEFAULT_HOSTNAME
  }
}

const trimTrailingSlash = (value: string) => value.replace(/\/+$/, "")

const buildFolderStructureSnippet = (hostname: string) => {
  return `site-rebuild/
 ├── ${hostname}/
 │    ├── index.html
 │    ├── about/
 │    ├── images/
 │    └── ...`
}

const buildRipgrepCommand = (hostname: string) =>
  `rg -o '<p>.*?</p>|<h[1-6]>.*?</h[1-6]>' ./${hostname} > all_text_raw.html`

const buildSitemapCommand = (baseUrl: string) => `${trimTrailingSlash(baseUrl)}/sitemap.xml`

const buildInstructionsSnippet = (baseUrl: string) => {
  const normalizedBase = trimTrailingSlash(baseUrl)
  return `echo "Website rebuild project for ${normalizedBase}
- Use Next.js + Tailwind
- Keep copy identical to original
- Modernize layout only" > .codex/instructions.md`
}

const buildFolderOverviewSnippet = (hostname: string) => {
  return `site-rebuild/
 ├── ${hostname}/          ← downloaded site
 ├── all_text_raw.txt      ← readable copy for Codex
 ├── sitemap.xml           ← structure map (optional)
 ├── .codex/
 │    ├── instructions.md
 │    └── current-site.md
 ├── package.json          ← generated by Codex
 ├── pages/
 ├── components/
 └── public/`
}

export default function SiteRebuildDynamicSteps() {
  const [inputValue, setInputValue] = useState("")

  const commandUrl = useMemo(() => deriveCommandUrl(inputValue), [inputValue])
  const hostname = useMemo(() => getHostnameFromUrl(commandUrl), [commandUrl])
  const folderStructureSnippet = useMemo(() => buildFolderStructureSnippet(hostname), [hostname])
  const ripgrepCommand = useMemo(() => buildRipgrepCommand(hostname), [hostname])
  const sitemapCommand = useMemo(() => buildSitemapCommand(commandUrl), [commandUrl])
  const instructionsSnippet = useMemo(() => buildInstructionsSnippet(commandUrl), [commandUrl])
  const folderOverviewSnippet = useMemo(() => buildFolderOverviewSnippet(hostname), [hostname])

  return (
    <>
      <article id="step-2" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">step 2</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">
            download the entire website snapshot
          </h3>
          <p className="text-base text-neutral-600">
            Use <span className="font-semibold text-neutral-800">wget</span> to grab every reachable page and its assets directly to
            disk.
          </p>
        </div>
        <div className="space-y-4">
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Install wget (if needed):</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{`brew install wget`}</code>
            </pre>
          </div>
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Download the live site:</p>
            <WgetCommandBuilder
              value={inputValue}
              onValueChange={setInputValue}
              commandUrl={commandUrl}
            />
            <p className="mt-3 text-sm text-neutral-600">
              <span className="font-semibold text-neutral-800">Flags in plain English:</span>
            </p>
            <ul className="mt-2 space-y-2 text-sm text-neutral-600 sm:text-base">
              <li>
                <span className="font-semibold text-neutral-800">-r</span> → recursive crawl so linked pages come with it.
              </li>
              <li>
                <span className="font-semibold text-neutral-800">-l inf</span> → crawl depth stays open until links run out.
              </li>
              <li>
                <span className="font-semibold text-neutral-800">-p</span> → pulls required assets like images, styles, and scripts.
              </li>
              <li>
                <span className="font-semibold text-neutral-800">-E</span> → adds <code className="rounded bg-neutral-100 px-1 py-0.5">.html</code>{" "}
                extensions so files open cleanly.
              </li>
              <li>
                <span className="font-semibold text-neutral-800">-k</span> → rewrites links for offline use.
              </li>
              <li>
                <span className="font-semibold text-neutral-800">-nc</span> → skips files you already downloaded.
              </li>
            </ul>
          </div>
          <div className="rounded-2xl border border-neutral-200 bg-white p-5 text-sm text-neutral-600 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Expected structure:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-950 p-4 text-xs text-white sm:text-sm">
              <code>{folderStructureSnippet}</code>
            </pre>
          </div>
        </div>
      </article>

      <article id="step-6" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">step 6</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">run codex locally</h3>
          <p className="text-base text-neutral-600">
            With context in place, let Codex generate the rebuild in a fresh Next.js project.
          </p>
        </div>
        <div className="space-y-4">
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Export your OpenAI key first:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{`export OPENAI_API_KEY="your_api_key_here"`}</code>
            </pre>
          </div>
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Ask Codex for the rebuild:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>
{`codex ask "Rebuild this website locally with the same text and structure using Next.js and Tailwind." \\
  --with .codex/instructions.md .codex/current-site.md`}
              </code>
            </pre>
            <p className="mt-3 text-sm text-neutral-600">
              Codex writes directly into the current folder — expect directories like <code className="rounded bg-neutral-100 px-1 py-0.5">pages/</code>,{" "}
              <code className="rounded bg-neutral-100 px-1 py-0.5">components/</code>, and <code className="rounded bg-neutral-100 px-1 py-0.5">public/</code>.
            </p>
          </div>
        </div>
      </article>

      <article id="step-7" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">step 7</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">
            preview the rebuilt site on localhost
          </h3>
          <p className="text-base text-neutral-600">
            Run the usual Next.js dev workflow and confirm the copy, layout, and routes match the original.
          </p>
        </div>
        <pre className="overflow-x-auto rounded-2xl bg-neutral-950 p-5 text-sm text-white shadow-sm">
          <code>
{`npm install
npm run dev`}
          </code>
        </pre>
        <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
          <p className="font-semibold text-neutral-800">Visit the local build:</p>
          <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
            <code>{`http://localhost:3000`}</code>
          </pre>
        </div>
      </article>

      <article id="folder-overview" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">reference</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">
            folder layout when you’re done
          </h3>
          <p className="text-base text-neutral-600">
            Keep this snapshot intact — it&apos;s the fastest way to iterate on the rebuild, hand assets to teammates, or version control the work.
          </p>
        </div>
        <pre className="overflow-x-auto rounded-2xl bg-neutral-950 p-5 text-sm text-white shadow-sm">
          <code>{folderOverviewSnippet}</code>
        </pre>
      </article>

      <article id="step-3" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">step 3</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">
            pull the actual copy into plain text
          </h3>
          <p className="text-base text-neutral-600">
            Optional, but it helps Codex keep every headline and paragraph accurate.
          </p>
        </div>
        <div className="space-y-4">
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Install ripgrep:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{`brew install ripgrep`}</code>
            </pre>
          </div>
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Extract headings and paragraphs:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{ripgrepCommand}</code>
            </pre>
            <p className="mt-3 font-semibold text-neutral-800">Strip the HTML tags:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{`sed -E 's/<[^>]+>//g' all_text_raw.html > all_text_raw.txt`}</code>
            </pre>
            <p className="mt-3 text-sm text-neutral-600">
              Result: a clean <code className="rounded bg-neutral-100 px-1 py-0.5">all_text_raw.txt</code> file ready for Codex context.
            </p>
          </div>
        </div>
      </article>

      <article id="step-4" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">step 4</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">
            grab the sitemap (if one exists)
          </h3>
          <p className="text-base text-neutral-600">
            A live <code className="rounded bg-neutral-100 px-1 py-0.5">sitemap.xml</code> gives Codex a definitive page list.
          </p>
        </div>
        <pre className="overflow-x-auto rounded-2xl bg-neutral-950 p-5 text-sm text-white shadow-sm">
          <code>{`curl -O ${sitemapCommand}`}</code>
        </pre>
      </article>

      <article id="step-5" className="space-y-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-neutral-500">step 5</p>
          <h3 className="text-2xl font-semibold lowercase text-neutral-900 sm:text-3xl">
            prep the codex context folder
          </h3>
          <p className="text-base text-neutral-600">
            Codex reads context from the <span className="font-semibold text-neutral-800">.codex</span> directory — keep instructions
            and source text here.
          </p>
        </div>
        <div className="space-y-4">
          <pre className="overflow-x-auto rounded-2xl bg-neutral-950 p-5 text-sm text-white shadow-sm">
            <code>{`mkdir .codex`}</code>
          </pre>
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Add project instructions:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{instructionsSnippet}</code>
            </pre>
          </div>
          <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-700 shadow-sm sm:text-base">
            <p className="font-semibold text-neutral-800">Copy extracted text for Codex:</p>
            <pre className="mt-3 overflow-x-auto rounded-xl bg-neutral-900 p-4 text-xs text-white sm:text-sm">
              <code>{`cp all_text_raw.txt .codex/current-site.md`}</code>
            </pre>
          </div>
        </div>
      </article>
    </>
  )
}
